<a href="https://colab.research.google.com/github/AmatHub21/Latihan-Esmeble_Sklearn_byest-/blob/main/PENGUKURAN%20KEDEKATAN%20DAN%20SIMILARITAS%20DATA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
from scipy.spatial.distance import euclidean, cityblock, minkowski

A = np.array([2, 3])
B = np.array([5, 7])

print(euclidean(A, B))
print(cityblock(A, B))
print(minkowski(A, B, p=3))

import numpy as np
from sklearn.preprocessing import MinMaxScaler, StandardScaler

data = np.array([[2, 2000000], [5, 7000000]])

minmax = MinMaxScaler().fit_transform(data)
zscore = StandardScaler().fit_transform(data)

print(minmax)
print(zscore)

import numpy as np

def smc(p, q):
    p, q = np.array(p), np.array(q)
    return np.sum(p == q) / len(p)

print(smc([1,0,1,1,0], [1,0,0,1,1]))

from sklearn.metrics import jaccard_score

p = [1,0,1,1,0]
q = [1,0,0,1,1]

print(jaccard_score(p, q))

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

docs = ["data mining", "machine learning"]

tfidf = TfidfVectorizer().fit_transform(docs)
print(cosine_similarity(tfidf))

5.0
7
4.497941445275415
[[0. 0.]
 [1. 1.]]
[[-1. -1.]
 [ 1.  1.]]
0.6
0.5
[[1. 0.]
 [0. 1.]]
